# Generated by Django 6.0.3 on 2026-03-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
